name: Daily Java Upload

on:
  schedule:
    - cron: '0 6 * * *'

  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
        

      - name: Run Upload Script
        run: python upload.py

      - name: Commit and Push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add .

          git commit -m "Daily Java Upload" || echo "No changes"

          git push
